apiVersion: v1
kind: List
metadata:
 namespace: zabbix
items:
  - apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
     name: db-secret
     namespace: zabbix
    data:
     db-zbx-user: "QWRtaW5pc3RyYWRvcg=="
     db-zbx-pass: "UGFzc3dvcmQuLiEh"
     db-zbx-name: "TWVsaURiVGVzdAo="
     db-zbx-host: "dGVycmFmb3JtLTIwMjQwMzIyMjAwMTQwMTczMDAwMDAwMDAxLmM3YW0zbGNxcGVpaC51cy1lYXN0LTIucmRzLmFtYXpvbmF3cy5jb20="